version: "3"

services:
  db:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  gotodos:
    build: ./goTodos
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/?sslmode=disable
    volumes:
      - ./goTodos:/go/src/goTodos
    depends_on:
      - db
    links:
      - db
